### ISSUE TITLE
[SUGGESTION] esx_policejob compatible

### ISSUE THREAD

**Issue by Akuramu** [prefech/Prefech_ALPR#2]
Hi ! 

Thanks to all the Prefech for this incredible and simplist scripts, it work very well ! 

Even if this addon it almost perfect, i want to suggest to you something; 

My suggestion is to make Prefech_ALPR compatible with esx_policejob. 

You are going to say "Whot, bruh ? Wtf ??", let me explain : 

To make esx_policejob compatible, we need to add the jobs permissions to the police job
The notifications will be restricted to the police job only (if we enabled it on config/config.lua) (also for the plates commands)

**Comment by JokeDevil** [comment]
Suggestions are on discord.
https://prefech.com/discord
